### ISSUE TITLE
voku/portable-utf8 dependency

### ISSUE THREAD

**Issue by Hackwar** [wamania/php-stemmer#30] opened 2023-02-27 12:32 UTC
Hello, thank you for your work with the stemmer. Joomla has gotten a bug report that [voku/portable-utf8](https://github.com/voku/portable-utf8) has a problem on PHP 8.2. (https://github.com/joomla/joomla-cms/issues/39512) It turns out that this is only used from your php-stemmer AND that voku already fixed this in their latest 6.0.x versions. From my perspective 6.0.12 should work perfectly fine with php-stemmer, since none of the code you are using has been changed in the 6.0 release. Would it be possible for you to update your composer.json to require voku/portable-utf8 to "^5.4|^6.0"? That would help us with Joomla 5.0.

The big question would be, if you could also do another release for 2.x with that change as well. Then we could fix this issue in Joomla 4.x as well. Thank you!

**Comment by HLeithner** [comment] 2023-02-27 12:41
if I understand you correctly you want this PR https://github.com/wamania/php-stemmer/pull/26 merged?

**Comment by Hackwar** [comment] 2023-02-27 12:43
Indeed.  Now I feel stupid. 😄 closing again.

**Comment by Hackwar** [comment] 2023-02-27 12:44
Actually no, I'm opening this up again, because the question would remain if we could have this in version 2.x as well.

**Comment by kokoshneta** [comment] 2023-06-04 10:50
Hijacking this thread a little bit, sorry:

The commit of #26 three weeks ago (presumably) fixed this issue, but since that commit doesn’t seem to have been associated with a 3.0.1 tag or a new release, and thus hasn’t been pushed to Packagist, the issue is not quite fixed after all. If you do not require this package yourself, but have other packages that do (such as Laravel Scout’s database driver), a simple `composer update` won’t update this package, since it’s still at version 3.0.0.

Could you re-tag the most recent commit to a higher version than 3.0.0 and make sure it’s pushed to Packagist, so that Composer can automatically pull in the new version?

**Comment by HLeithner** [comment] 2023-06-04 19:52
I tagged 3.0.1, Joomla 5.0 already uses the new tag and seems to work.

I'm closing this since it's solved.

**Closed as completed by HLeithner** 2023-06-04 19:52 UTC
